# Generated by Django 5.2.17 on 2026-10-05 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('date', models.DateField(primary_key=True, serialize=False, verbose_name='日付')),
                ('name', models.CharField(max_length=50, verbose_name='祝日の名前')),
            ],
            options={
                'verbose_name': '祝日',
                'db_table': 'holidays',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('id', models.SmallIntegerField(default=1, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_symbol', models.CharField(choices=[('yen_sign', '¥'), ('yen_text', '円'), ('none', 'なし')], default='yen_sign', max_length=10, verbose_name='通貨記号')),
                ('use_thousands_separator', models.BooleanField(default=True, verbose_name='桁区切り')),
                ('month_start_day', models.SmallIntegerField(default=1, verbose_name='月の開始日')),
                ('month_start_holiday_rule', models.CharField(choices=[('none', 'そのまま'), ('previous', '前にずらす'), ('next', '後にずらす')], default='none', max_length=10, verbose_name='開始日が土日祝日のとき')),
                ('week_start', models.CharField(choices=[('sunday', '日曜'), ('monday', '月曜')], default='sunday', max_length=10, verbose_name='週の開始曜日')),
                ('theme', models.CharField(choices=[('light', 'ライト'), ('dark', 'ダーク'), ('system', '端末に合わせる')], default='system', max_length=10, verbose_name='テーマ')),
                ('tax_rounding', models.CharField(choices=[('floor', '切り捨て'), ('round_half_up', '四捨五入'), ('ceiling', '切り上げ')], default='floor', max_length=20, verbose_name='消費税の端数処理')),
                ('default_amount_input_type', models.CharField(choices=[('tax_included', '税込'), ('tax_excluded', '税抜')], default='tax_included', max_length=20, verbose_name='金額の入力の初期値')),
                ('default_tax_rate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.taxrate', verbose_name='既定の税率')),
            ],
            options={
                'verbose_name': '設定',
                'db_table': 'app_settings',
                'constraints': [models.CheckConstraint(condition=models.Q(('id', 1)), name='app_settings_single_row'), models.CheckConstraint(condition=models.Q(('month_start_day__gte', 0), ('month_start_day__lte', 30)), name='app_settings_month_start_day_range')],
            },
        ),
    ]
