# Generated by Django 5.2.17 on 2026-10-05 05:47

import django.db.models.deletion
import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('kind', models.CharField(choices=[('income', '収入'), ('expense', '支出'), ('transfer', '振替')], max_length=10, verbose_name='種類')),
                ('date', models.DateField(verbose_name='日付')),
                ('amount', models.BigIntegerField(verbose_name='金額')),
                ('amount_input_type', models.CharField(blank=True, choices=[('tax_included', '税込'), ('tax_excluded', '税抜')], max_length=20, null=True, verbose_name='金額の入力')),
                ('description', models.CharField(blank=True, default='', max_length=100, verbose_name='内容')),
                ('memo', models.CharField(blank=True, default='', max_length=500, verbose_name='メモ')),
                ('source', models.CharField(choices=[('manual', '手入力'), ('recurring', '定期収支'), ('csv', 'CSV 取り込み')], default='manual', max_length=10, verbose_name='登録元')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='masters.asset', verbose_name='資産')),
                ('transfer_to_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transfers', to='masters.asset', verbose_name='振替先の資産')),
            ],
            options={
                'verbose_name': '明細',
                'db_table': 'transactions',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TransactionLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('tax_rate_value', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='税率の値')),
                ('amount_excl', models.BigIntegerField(verbose_name='税抜額')),
                ('tax_amount', models.BigIntegerField(verbose_name='消費税額')),
                ('amount_incl', models.BigIntegerField(verbose_name='税込額')),
                ('sort_order', models.IntegerField(default=0, verbose_name='表示順')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transaction_lines', to='masters.category', verbose_name='分類')),
                ('tax_rate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transaction_lines', to='masters.taxrate', verbose_name='税率')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='ledger.transaction', verbose_name='明細')),
            ],
            options={
                'verbose_name': '明細の内訳',
                'db_table': 'transaction_lines',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['date'], name='transactions_date_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['asset', 'date'], name='transactions_asset_date_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['transfer_to_asset', 'date'], name='transactions_to_date_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['description'], name='transactions_desc_idx'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ['income', 'expense', 'transfer'])), name='transactions_kind_valid'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', -99999999), ('amount__lte', 99999999), models.Q(('amount', 0), _negated=True)), name='transactions_amount_range'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('kind', 'expense'), ('amount__gt', 0), _connector='OR'), name='transactions_amount_negative_only_expense'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('amount_input_type__isnull', True), ('kind', 'transfer'), ('transfer_to_asset__isnull', False)), models.Q(models.Q(('kind', 'transfer'), _negated=True), ('amount_input_type__isnull', False), ('transfer_to_asset__isnull', True)), _connector='OR'), name='transactions_transfer_fields'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('transfer_to_asset__isnull', True), models.Q(('asset', models.F('transfer_to_asset')), _negated=True), _connector='OR'), name='transactions_transfer_different_assets'),
        ),
        migrations.AddIndex(
            model_name='transactionline',
            index=models.Index(fields=['category'], name='transaction_lines_category_idx'),
        ),
        migrations.AddConstraint(
            model_name='transactionline',
            constraint=models.CheckConstraint(condition=models.Q(('amount_incl', django.db.models.expressions.CombinedExpression(models.F('amount_excl'), '+', models.F('tax_amount')))), name='transaction_lines_amount_sum'),
        ),
        migrations.AddConstraint(
            model_name='transactionline',
            constraint=models.CheckConstraint(condition=models.Q(('tax_rate_value__gte', 0), ('tax_rate_value__lte', 100)), name='transaction_lines_tax_rate_value_range'),
        ),
    ]
