# Generated by Django 5.2.17 on 2026-10-05 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssetGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='名前')),
                ('sort_order', models.IntegerField(default=0, verbose_name='並び順')),
            ],
            options={
                'verbose_name': '資産グループ',
                'db_table': 'asset_groups',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TaxRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='名前')),
                ('rate', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='税率（%）')),
                ('is_hidden', models.BooleanField(default=False, verbose_name='非表示')),
                ('sort_order', models.IntegerField(default=0, verbose_name='並び順')),
            ],
            options={
                'verbose_name': '税率',
                'db_table': 'tax_rates',
                'ordering': ['sort_order', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('rate__gte', 0), ('rate__lte', 100)), name='tax_rates_rate_range')],
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='名前')),
                ('opening_balance', models.BigIntegerField(default=0, verbose_name='開始残高')),
                ('is_credit_card', models.BooleanField(default=False, verbose_name='クレジットカード')),
                ('closing_day', models.SmallIntegerField(blank=True, null=True, verbose_name='締め日')),
                ('payment_month_offset', models.SmallIntegerField(blank=True, null=True, verbose_name='引き落とし月')),
                ('payment_day', models.SmallIntegerField(blank=True, null=True, verbose_name='引き落とし日')),
                ('is_hidden', models.BooleanField(default=False, verbose_name='非表示')),
                ('sort_order', models.IntegerField(default=0, verbose_name='並び順')),
                ('payment_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='paid_cards', to='masters.asset', verbose_name='引き落とし口座')),
                ('asset_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='masters.assetgroup', verbose_name='資産グループ')),
            ],
            options={
                'verbose_name': '資産',
                'db_table': 'assets',
                'ordering': ['sort_order', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('closing_day__isnull', False), ('is_credit_card', True), ('payment_account__isnull', False), ('payment_day__isnull', False), ('payment_month_offset__isnull', False)), models.Q(('closing_day__isnull', True), ('is_credit_card', False), ('payment_account__isnull', True), ('payment_day__isnull', True), ('payment_month_offset__isnull', True)), _connector='OR'), name='assets_card_fields'), models.CheckConstraint(condition=models.Q(('closing_day__isnull', True), models.Q(('closing_day__gte', 0), ('closing_day__lte', 30)), _connector='OR'), name='assets_closing_day_range'), models.CheckConstraint(condition=models.Q(('payment_day__isnull', True), models.Q(('payment_day__gte', 0), ('payment_day__lte', 30)), _connector='OR'), name='assets_payment_day_range'), models.CheckConstraint(condition=models.Q(('payment_month_offset__isnull', True), ('payment_month_offset__in', [1, 2]), _connector='OR'), name='assets_payment_month_offset_range')],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('kind', models.CharField(choices=[('income', '収入'), ('expense', '支出')], max_length=10, verbose_name='種類')),
                ('name', models.CharField(max_length=50, verbose_name='名前')),
                ('is_hidden', models.BooleanField(default=False, verbose_name='非表示')),
                ('sort_order', models.IntegerField(default=0, verbose_name='並び順')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='masters.category', verbose_name='親の分類')),
                ('default_tax_rate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.taxrate', verbose_name='既定の税率')),
            ],
            options={
                'verbose_name': '分類',
                'db_table': 'categories',
                'ordering': ['sort_order', 'id'],
                'indexes': [models.Index(fields=['kind', 'parent', 'sort_order'], name='categories_list_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('kind__in', ['income', 'expense'])), name='categories_kind_valid')],
            },
        ),
    ]
