# Generated by Django 5.2.17 on 2026-10-05 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ledger', '0001_initial'),
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('kind', models.CharField(choices=[('income', '収入'), ('expense', '支出'), ('transfer', '振替')], max_length=10, verbose_name='種類')),
                ('amount_input_type', models.CharField(blank=True, choices=[('tax_included', '税込'), ('tax_excluded', '税抜')], max_length=20, null=True, verbose_name='金額の入力')),
                ('amount', models.BigIntegerField(verbose_name='金額')),
                ('description', models.CharField(blank=True, default='', max_length=100, verbose_name='内容')),
                ('memo', models.CharField(blank=True, default='', max_length=500, verbose_name='メモ')),
                ('frequency', models.CharField(choices=[('monthly', '毎月◯日'), ('month_end', '毎月末'), ('weekly', '毎週◯曜日'), ('yearly', '毎年◯月◯日')], max_length=10, verbose_name='周期')),
                ('day_of_month', models.SmallIntegerField(blank=True, null=True, verbose_name='日')),
                ('weekday', models.SmallIntegerField(blank=True, null=True, verbose_name='曜日')),
                ('month', models.SmallIntegerField(blank=True, null=True, verbose_name='月')),
                ('holiday_rule', models.CharField(choices=[('none', 'そのまま'), ('previous', '前にずらす'), ('next', '後にずらす')], default='none', max_length=10, verbose_name='土日祝日の扱い')),
                ('start_date', models.DateField(verbose_name='開始日')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='終了日')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recurring_items', to='masters.asset', verbose_name='資産')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recurring_items', to='masters.category', verbose_name='分類')),
                ('tax_rate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recurring_items', to='masters.taxrate', verbose_name='税率')),
                ('transfer_to_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_recurring_items', to='masters.asset', verbose_name='振替先の資産')),
            ],
            options={
                'verbose_name': '定期収支',
                'db_table': 'recurring_items',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='RecurringRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('scheduled_date', models.DateField(verbose_name='本来の登録日')),
                ('registered_date', models.DateField(verbose_name='登録した日付')),
                ('recurring_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='recurring.recurringitem', verbose_name='定期収支')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ledger.transaction', verbose_name='登録した明細')),
            ],
            options={
                'verbose_name': '定期収支の登録履歴',
                'db_table': 'recurring_runs',
            },
        ),
        migrations.AddConstraint(
            model_name='recurringitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('day_of_month__isnull', False), ('frequency', 'monthly'), ('month__isnull', True), ('weekday__isnull', True)), models.Q(('day_of_month__isnull', True), ('frequency', 'month_end'), ('month__isnull', True), ('weekday__isnull', True)), models.Q(('day_of_month__isnull', True), ('frequency', 'weekly'), ('month__isnull', True), ('weekday__isnull', False)), models.Q(('day_of_month__isnull', False), ('frequency', 'yearly'), ('month__isnull', False), ('weekday__isnull', True)), _connector='OR'), name='recurring_items_frequency_fields'),
        ),
        migrations.AddConstraint(
            model_name='recurringitem',
            constraint=models.CheckConstraint(condition=models.Q(('day_of_month__isnull', True), models.Q(('day_of_month__gte', 1), ('day_of_month__lte', 31)), _connector='OR'), name='recurring_items_day_of_month_range'),
        ),
        migrations.AddConstraint(
            model_name='recurringitem',
            constraint=models.CheckConstraint(condition=models.Q(('weekday__isnull', True), models.Q(('weekday__gte', 0), ('weekday__lte', 6)), _connector='OR'), name='recurring_items_weekday_range'),
        ),
        migrations.AddConstraint(
            model_name='recurringitem',
            constraint=models.CheckConstraint(condition=models.Q(('month__isnull', True), models.Q(('month__gte', 1), ('month__lte', 12)), _connector='OR'), name='recurring_items_month_range'),
        ),
        migrations.AddConstraint(
            model_name='recurringitem',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 1), ('amount__lte', 99999999)), name='recurring_items_amount_range'),
        ),
        migrations.AddConstraint(
            model_name='recurringitem',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='recurring_items_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='recurringitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('amount_input_type__isnull', True), ('category__isnull', True), ('kind', 'transfer'), ('tax_rate__isnull', True), ('transfer_to_asset__isnull', False)), models.Q(models.Q(('kind', 'transfer'), _negated=True), ('amount_input_type__isnull', False), ('category__isnull', False), ('tax_rate__isnull', False), ('transfer_to_asset__isnull', True)), _connector='OR'), name='recurring_items_transfer_fields'),
        ),
        migrations.AddConstraint(
            model_name='recurringrun',
            constraint=models.UniqueConstraint(fields=('recurring_item', 'scheduled_date'), name='recurring_runs_unique_occurrence'),
        ),
    ]
