# Generated by Django 5.2.17 on 2026-10-05 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0002_initial_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('base_amount', models.BigIntegerField(verbose_name='基本額')),
                ('category', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='budget', to='masters.category', verbose_name='分類')),
            ],
            options={
                'verbose_name': '予算',
                'db_table': 'budgets',
            },
        ),
        migrations.CreateModel(
            name='MonthlyBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('year_month', models.DateField(verbose_name='対象の年月')),
                ('amount', models.BigIntegerField(verbose_name='予算額')),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly', to='budgets.budget', verbose_name='予算')),
            ],
            options={
                'verbose_name': '月別予算',
                'db_table': 'monthly_budgets',
            },
        ),
        migrations.AddConstraint(
            model_name='budget',
            constraint=models.CheckConstraint(condition=models.Q(('base_amount__gte', 0)), name='budgets_base_amount_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='monthlybudget',
            constraint=models.UniqueConstraint(fields=('budget', 'year_month'), name='monthly_budgets_unique_month'),
        ),
        migrations.AddConstraint(
            model_name='monthlybudget',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='monthly_budgets_amount_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='monthlybudget',
            constraint=models.CheckConstraint(condition=models.Q(('year_month__day', 1)), name='monthly_budgets_first_day'),
        ),
    ]
